### ISSUE TITLE
Advanced playground saved state is shared between plugin test pages

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#498] opened 2020-12-01 18:32 UTC
**Category**

plugins

**Component**

@blockly/dev-tools

**Describe the bug**

The saved configuration state for the playground is saved under the same name for every plugin test page, meaning that loading the test page for a different plugin (e.g. on gh-pages) can open with the playground in a bad/unusable state and require a reset.

**Expected behavior**

State is saved under a more specific name.

**Additional context**

This is a problem for the plugin demo pages on gh-pages, because the demo should always initially load with the settings created by the test page.

**Comment by samelhusseini** [comment] 2020-12-01 18:54
Dupe of https://github.com/google/blockly-samples/issues/336 ?

**Closed as completed** 2020-12-01 18:54 UTC
Labels: type: bug
