### ISSUE TITLE
When using the blockly-react I get an uncaught error in the chrome console.

### ISSUE THREAD

**Issue by rvmeer** [RaspberryPiFoundation/blockly-samples#683] opened 2021-04-30 09:43 UTC
**Category**

Examples

**Component**

blockly-react

**Describe the bug**

When using the blockly-react I get an uncaught error in the chrome console.

![image](https://user-images.githubusercontent.com/16347444/116678098-3fce8b80-a9a9-11eb-80b3-87a19b4fd54c.png)

**To Reproduce**

Just drag a block from the toolbox into the workspace. Then drag a sub-block, inside e.g. an if statement block. Then you'll see the error in the chrome dev console.

**Expected behavior**

No uncaught error.

**Screenshots**

![image](https://user-images.githubusercontent.com/16347444/116678184-5379f200-a9a9-11eb-80e7-fb4dbd30c2a3.png)

**Additional context**

**Comment by alschmiedt** [comment] 2021-04-30 18:07
Hello!

Thanks for reporting. I am having trouble reproducing the issue. Here is a gif of what I tried: 
![React-gif](https://user-images.githubusercontent.com/23059043/116736013-2b3bc480-a9a4-11eb-83c1-46360018dca3.gif)


Have you pulled the most recent version of master? What web browser are you using?

**Comment by gonfunko** [comment] 2023-04-14 19:37
I'm not able to reproduce this either, and given the age of the bug I'll close it. If you're still experiencing this on the latest version feel free to reopen though!

**Closed as completed by gonfunko** 2023-04-14 19:37 UTC
Labels: type: bug, type: question, category: plugin
